name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - '*.md'
jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox
      - run: tox -e docs
